language: haskell
ghc: 7.8

sudo: false

install:
    - cabal install --only-dependencies --enable-tests
    - cabal install --force-reinstalls hpc-coveralls

script:
    - cabal configure --enable-tests --enable-library-coverage
    - cabal build
    - cabal test

after_script:
    - hpc-coveralls --exclude-dir=tests spec
